### ISSUE TITLE
Any Gedmo-based extension should check that the GedmoExtensionsServiceProvider is used

### ISSUE THREAD

**Issue by sisve** [laravel-doctrine/extensions#10]
Any Gedmo-based extension should check that the GedmoExtensionsServiceProvider is used, and throw an exception if it isn't. This should catch all configuration issues where someone (read: me) has a brain-freeze and enables the SoftDeleteableExtension without adding the GedmoExtensionsServiceProvider to config/app.php

**Comment by patrickbrouwers** [comment]
Like I responded on Slack, this won't be possible. As stated in the documentation GedmoSP is only for annotations, so we can’t throw an exception.
