### ISSUE TITLE
Loggable

### ISSUE THREAD

**Issue by najdias** [laravel-doctrine/extensions#23]
Hello,

I've a simple product model with "loggable" annotation and "versioned" annotation at name property.
My problem is when I update product name I see the ext_log_entries table and the log entry is there but there's no username associated. I am logged in with doctrine user provider driver.
Someone has this working?

**Comment by patrickbrouwers** [comment]
Check the order of service providers, DoctrineServiceProvider should be registered before Gedmo. (if you are using annotations or fluent)
