### ISSUE TITLE
Event "doctrine.extensions.booting" never happens in ServiceProvider

### ISSUE THREAD

**Issue by JoseClaudioADS** [laravel-doctrine/extensions#25]
Was error loading the annotations of Gedmo.

I investigated and saw that there was an event in ServiceProvider ("$ this-> app [ 'events'] -> listen ('doctrine.extensions.booting.'"), Which never happened not even found a reference to the event.

I removed that line and functioned normally. That was right?

**Comment by patrickbrouwers** [comment]
The event is fired in DoctrineServiceProvider and it's important that the listener stays in place.

Make sure the DoctrineServiceProvider is registered before the GedmoServiceProvider.

Also try and avoid calling any registry/em related stuff in other ServiceProvider (like Auth::user() e.g.). It will boot the entity manager when it's not necessary.

**Comment by JoseClaudioADS** [comment]
@patrickbrouwers Reallyit is called there. I believe you can be what you talked about calling EntityManager as Auth :: before.

I know I'm carrying him after Doctrine. And I believe that the Doctrine is being loaded after the ServicesProviders Laravel standards.

Once again the work will test and I submit the answers here. Thank you!

**Comment by JoseClaudioADS** [comment]
@patrickbrouwers Actually it is called there. I believe you can be what you talked about calling EntityManager as Auth :: before.

I know I'm carrying him after Doctrine. And I believe that the Doctrine is being loaded after the ServicesProviders Laravel standards.

Once again the work will test and I submit the answers here. Thank you!

**Comment by JoseClaudioADS** [comment]
Really. I was calling a service before. Shot and fall. Thank you!
