### ISSUE TITLE
Timestampable with Custom Type

### ISSUE THREAD

**Issue by ghost** [laravel-doctrine/extensions#26]
Hi,
Is there a way to use Timestampable with a custom type (CarbonDateTime, for example)?
It appears to be throwing an exception:
Field - [created_at] type is not valid and must be 'date', 'datetime' or 'time'.

**Comment by patrickbrouwers** [comment]
I'm afraid not, it looks baked into their code: https://github.com/Atlantic18/DoctrineExtensions/blob/master/doc/timestampable.md#timestampable-annotations
