### ISSUE TITLE
Extension user loading loop

### ISSUE THREAD

**Issue by qskousen** [laravel-doctrine/extensions#33]
Using Laravel 5.4. Doctrine is handling the users model. 

When certain extensions are enabled (those using `ResolveUserDecorator`) Doctrine, on loading, will attempt to load the user, due to this part in `ResolveUserDecorator.php:70`:

```php
if ($this->auth->check()) {
       call_user_func([$this->wrapped, $this->userSetterMethod], $this->auth->user());
}
````

Since the user is loaded by Doctrine, Laravel will attempt to load Doctrine, which will attempt to load the user... You get the idea. 

How can this be worked around to prevent a loop?

**Comment by patrickbrouwers** [comment]
Closing this as a PR has been submitted to fix it.
