### ISSUE TITLE
v1.0.13 is causing a php segfault

### ISSUE THREAD

**Issue by LavaToaster** [laravel-doctrine/extensions#38]
I'm looking into it right, but after some amount of time we managed to trace it back to this package. We've pinned this dependency to v1.0.12 and everything works again.

**Comment by LavaToaster** [comment]
It's recursively trying to boot the doctrine user provider.

![](https://share.adamlav.in/prOF/Screen%20Shot%202018-03-01%20at%2011.32.06.png)

**Comment by Lavoaster** [comment]
![](https://share.adamlav.in/prOF/Screen%20Shot%202018-03-01%20at%2011.32.06.png)
