### ISSUE TITLE
BeberleiExtensions doesn't register properly in laravel 5.7

### ISSUE THREAD

**Issue by hshahdoost** [laravel-doctrine/extensions#43]
I'm using the following packages and have just upgraded into Laravel 5.7 (from 5.4)
```
        "laravel-doctrine/orm": "1.4.*",
        "laravel-doctrine/extensions": "1.0.*",
        "beberlei/DoctrineExtensions": "1.1.5",
        "gedmo/doctrine-extensions": "^2.4",
```

I don't know why this is happening, but after upgrading into Laravel 5.7, I can no longer use `BeberleiExtensions` methods such as `Month`. I have removed the updated package service providers from my app config and kept **beberlei** and **gedmo** there. So far everything. Here is how I have registered the service providers

```

        /*
         * Application Service Providers...
         */
        App\Providers\AppServiceProvider::class,
        App\Providers\AuthServiceProvider::class,
        // App\Providers\BroadcastServiceProvider::class,
        App\Providers\EventServiceProvider::class,
        App\Providers\RouteServiceProvider::class,

        LaravelDoctrine\Extensions\BeberleiExtensionsServiceProvider::class,
        LaravelDoctrine\Extensions\GedmoExtensionsServiceProvider::class,
```

The Gedmo library is working fine, but Berberlei doesn't get registered properly, Both of them are added to Providers in bootstrap and are registered after LaravelDoctrine. But there is a difference in the way Beberlei is registered which makes this happen.
Beberlei is using the following code to register it's datetime functions in [BeberleiExtensionsServiceProvider](https://github.com/laravel-doctrine/extensions/blob/develop/src/BeberleiExtensionsServiceProvider.php)
```
        $manager->extendAll(function (Configuration $configuration) {
            $configuration->setCustomDatetimeFunctions($this->datetime);
            $configuration->setCustomNumericFunctions($this->numeric);
            $configuration->setCustomStringFunctions($this->string);
        });
```
While Gedmo is using a more sophisticated way of registering it's annotations (You can see it [here](https://github.com/laravel-doctrine/extensions/blob/develop/src/GedmoExtensionsServiceProvider.php))

The callback of `$manager->extendAll` is never called for some reason, while the callback of Gedmo is called properly.

**Comment by hshahdoost** [comment]
The problem was solved by creating a new ServiceProvider for Beberlei but registering it's methods the way Gedmo was doing it
```
class BeberleiExtensionsServiceProvider extends BaseServiceProvider
{
    public function boot(DoctrineManager $manager){

    }

    /**
     * Register the service provider.
     * @return void
     */
    public function register()
    {
        $this->app['events']->listen('doctrine.extensions.booting', function () {
            /**
             * @var Registry $registry
             */
            $registry = $this->app->make('registry');

            foreach ($registry->getManagers() as $manager) {
                $configuration = $manager->getConfiguration();
                $configuration->setCustomDatetimeFunctions($this->datetime);
                $configuration->setCustomNumericFunctions($this->numeric);
                $configuration->setCustomStringFunctions($this->string);
            }
        });
    }
}
```

**Comment by whizsid** [comment]
Can reproduce this issue in laravel `8.1` too. @hshahdoost 's fix is still working.

**Comment by dpslwk** [comment]
This is working fine for me. We would need a more detailed error and example code of what is not working to help more.

**Comment by TomHAnderson** [comment]
This issue has expired. Reopen if you're still having issues.
