### ISSUE TITLE
Laravel 6 support?

### ISSUE THREAD

**Issue by dhsananias** [laravel-doctrine/extensions#49]
➜  project composer require "laravel-doctrine/extensions"      
Using version ^1.2 for laravel-doctrine/extensions
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: laravel-doctrine/orm[1.6.x-dev, 1.5.7].
    - Can only install one of: laravel-doctrine/orm[1.6.x-dev, 1.5.7].
    - Can only install one of: laravel-doctrine/orm[1.6.x-dev, 1.5.7].
    - laravel-doctrine/extensions 1.2.0 requires laravel-doctrine/orm 1.6.* -> satisfiable by laravel-doctrine/orm[1.6.x-dev].
    - Installation request for laravel-doctrine/extensions ^1.2 -> satisfiable by laravel-doctrine/extensions[1.2.0].
    - Installation request for laravel-doctrine/orm (locked at 1.5.7, required as 1.5.*) -> satisfiable by laravel-doctrine/orm[1.5.7].

Installation failed, reverting ./composer.json to its original content.

**Comment by kisuka** [comment]
@dhsananias you need to use the 1.1 branch for Laravel 6 because the 1.2 branch requires illuminate 7.0 packages, which are only for Laravel 7.

- 1.2 = Laravel 7
- 1.1 = Laravel 6
- 1.0 = Laravel 5

**Comment by eigan** [comment]
As @kisuka pointed out, use 1.1.

```
composer require laravel-doctrine/extensions "~1.1"
```
