### ISSUE TITLE
Add support for Laravel 8

### ISSUE THREAD

**Issue by martio** [laravel-doctrine/extensions#50]
Hi! Please support for Laravel ver. 8.x 👍

**Comment by eigan** [comment]
1.3.0 released thanks to @sojeda in #51, please try it out! :)

**Comment by froccsos** [comment]
Hi! I think you should check this @eigan: 
```
requires
php: >=7.2.5
illuminate/auth: ^7.0
illuminate/config: ^7.0
illuminate/contracts: ^7.0
illuminate/http: ^7.0
illuminate/support: ^7.0
laravel-doctrine/orm: 1.6.*
```
From: https://packagist.org/packages/laravel-doctrine/extensions#1.3.0

**Comment by eigan** [comment]
Seems like I tagged before pulling after merge :man_facepalming:! Thanks for letting me know. Will fix asap.

**Comment by eigan** [comment]
Fixed

**Comment by froccsos** [comment]
Thank you!
