### ISSUE TITLE
Tag 1.5.0 and 1.4.0 are the same

### ISSUE THREAD

**Issue by xClaireLouisex** [laravel-doctrine/extensions#57]
Hey, we've tried to install 1.5 to upgrade to Laravel 9 but it can't resolve conflicts in the composer dependencies.

When investigating, I noticed the dates of 1.5 & 1.4 are the same on packagist. The tags 1.5 and 1.4 target the same commit in this repo.

https://github.com/laravel-doctrine/extensions/blob/1.5.0/composer.json still shows illuminate/http locked to 8.0 for example. Support for Laravel 9 is only accessible via 1.x-dev tag in packagist.org.

Could this be updated at some point? I'll target 1.x-dev for now.
Appreciate the work on this repo!

**Comment by eigan** [comment]
Sorry about that. I forgot to pull before tagging 🤦🏻‍♂️ 

Tagged 1.5.1 now.
