### ISSUE TITLE
uploadable

### ISSUE THREAD

**Issue by mitjarobic** [laravel-doctrine/extensions#7]
Hello, 

i am trying to use the uploadable extension. How do i get the $listener variable used in the documentation example? 

```
$listener->setDefaultPath('/my/path');

$file = new File();

$listener->addEntityFileInfo($file, new CustomFileInfo('/path/to/file.txt'));

$em->persist($file);
$em->flush();
```

**Comment by patrickbrouwers** [comment]
@jee7 can you answer this question?

**Comment by jee7** [comment]
Of course. You see, the [UploadableExtensionServiceProvider](https://github.com/laravel-doctrine/extensions/blob/1.0/src/Uploadable/UploadableExtensionServiceProvider.php) registers a singleton with the alias of the class name of UploadableListener.

You can use that to fetch the singleton anywhere in your code (or inject it as an hard dependency if you want).

Using the `app()` shortcut:

```
$listener = app(UploadableListener::class);
```

**Comment by mitjarobic** [comment]
Thank you, but i can not get it to work. Is there something else I should set in doctrine.php except uncomment the 'LaravelDoctrine\Extensions\Uploadable\UploadableExtension::class' which is missing by default.

It seems the $this->fileInfoObjects is empty in onFlush method 

https://github.com/Atlantic18/DoctrineExtensions/blob/master/lib/Gedmo/Uploadable/UploadableListener.php#L144

although i set it with

```
$listener->addEntityFileInfo($file, new CustomFileInfo('/path/to/file.txt'));
```

**Comment by jee7** [comment]
Did you add the `LaravelDoctrine\Extensions\Uploadable\UploadableExtensionServiceProvider::class` to the list of service providers (the `providers` key) in your `app.php` config?

**Comment by mitjarobic** [comment]
That was it, thank you!

**Comment by jee7** [comment]
Btw, there is also an Uploadable facade that you can use. See my last comment in the [PR](https://github.com/laravel-doctrine/extensions/pull/3).

You're welcome. Don't know, why the service provider registration seems to be missing from the doc.

**Comment by patrickbrouwers** [comment]
Seems like the docs weren't updated after your PR. Could you make a PR with some notes about the singleton?
